---
# run this playbook to install saltminions
- hosts: saltminions
  become: yes
  gather_facts: yes

  tasks:
  - name: place salt repo for RedHat family
    template:
      src: template/salt.repo.j2
      dest: /etc/yum.repos.d/salt.repo
      mode: '0644'
    when: ansible_os_family == "RedHat"

  - name: install common pkgs for RedHat family
    yum:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - "{{ rpm_pkg }}"
    when: ansible_os_family == "RedHat"

  - name: install common packages for Debian family
    apt:
      name: "{{ deb_package }}"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Add salt key for Debian family
    get_url:
      url: "{{ deb_key_url }}"
      dest: /etc/apt/keyrings/salt-archive-keyring.pgp
    when: ansible_os_family == "Debian"

  - name: Add salt repo for Debian family
    get_url:
      url: "{{ deb_repo_url }}"
      dest: /etc/apt/sources.list.d/salt.sources
    when: ansible_os_family == "Debian"

  - name: start firewalld service
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Opening firewall ports in saltminions
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items: "{{ salt_port }}"
    ignore_errors: true
    when: ansible_os_family == "RedHat"
       or ansible_os_family == "Debian"
       or ansible_os_family == "Suse"

  - name: reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: install salt-minion
    package:
      name: salt-minion
      state: latest
      update_cache: yes
    when: ansible_os_family == "RedHat"
       or ansible_os_family == "Debian"
       or ansible_os_family == "Suse"

  - name: Run the salt-minion service
    service:
      name: salt-minion
      enabled: true
      state: started

  - name: Setting salt-master IP in /etc/salt/minion file
    lineinfile:
      path: /etc/salt/minion
      regexp: '^#master:|^master:'
      line: 'master: saltmaster'

  - name: Setting minion_id in /etc/salt/minion_id file
    template:
      src: template/minion_id.j2
      dest: /etc/salt/minion_id
      mode: 0644

  - name: Restart salt-minion service
    service:
      name: salt-minion
      state: restarted
