--- 
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Running salt-master service
      service:
        name: salt-master
        enabled: true
        state: started
                                            
    - name: Running salt-minion service
      service:
        name: salt-minion
        enabled: true
        state: started
